== Ressources Développeurs Neo4j

=== Vous voulez participer à la traduction des guides développeurs ?

Nous en serions extrêmement ravis !

Le plus simple est de contacter le mailto:christophe@graphaware.com[Le responsable de la traduction FR] afin d'avoir
un échange rapide et quelques conseils afin d'optimiser votre processus de traduction.

---

Ceci est le dépôt du contenu de la section _ressources développeurs_ du site http://neo4j.fr .

Le contenu est écrit au format textuel en http://asciidoctor.org[AsciiDoc] et rendu avec asciidoctor utilisant des templates HTML
et envoyé vers la branche `gh-pages` ou sur wordpress.

Installez les ruby gems asciidoctor (1.5.1) en exécutant `bundle install` dans le répertoire principal.

Vous pouvez rendre un simple document vers son `index.html` en exécutant `./render.sh path/vers/doc.adoc` + 
(e.g. `./render.sh in-production/guide-cloud-deployment/guide-cloud-deployment.adoc`) ou effectuer le rendu de toutes les pages en exécutant tout simplement `./render.sh`

Vous pouvez ouvrir le fichier `index.html` localement afin de vérifier le rendu/prévisualisation, ou lancer le serveur via le script `http` du répertoire principal et ensuite vous rendre à l'adresse http://localhost:8000/developer-resources-fr/

=== Guides

La majorité des documents des sections `ressources développeurs` sont organisés comme guides.
Ces guides ont une structure consistente et un usage similaire du langage et des contenus.
Chacun de ces guides vit dans son propre répertoire et est rendu vers un fichier `index.html` pour publication.
Vous pouvez effectuer le processus du rendu en exécutant `./render.sh` en ligne de commande.

Un guide a cette sructure générale:

1. but de ce guide
2. prérequis avec des liens vers les sections relatantes
3. expérience recommandée (débutant, intermédiaire, avancé)
4. de multiples sections et sous-sections représentant le contenu
utilisez un langage agréable et aidant, pas trop complexe ou éloquent avec des exemples de code, images ou vidéos
5. chaque section de haut niveau (`===`) peut être suivie d'une section de côté (sidebar) avec des liens qui seront rendus sur le côté droit pointant vers des informations (liens internes, appels à action, liens externes)

Veuillez regarder link:./guide_template.adoc[le fichier guide d'exemple] pour un blueprint de la structure nécessaire du document et link:./guide_template.html[son rendu].

==== Calls to Action

* http://neo4j.com/events?type=Webinar[Webinar Registration]
* http://neo4j.com/books[Book Downloads]
* http://neo4j.com/newsletter/[Newsletter Registration]
* http://neo4j.com/online-training[Online Training]
* http://neo4j.com/events?type=Training[Offline Training Classes]
* http://neo4j.com/download[Neo4j Download]
* http://neo4j.com/?s=+whitepaper[Whitepapers]

==== Projets internes et externes

* Autres ressources développeurs et le site neo4j.fr
* http://neo4j.com/docs/chunked/stable[Pages du manuel] et Articles
* Blog Posts (http://neo4j.com/blog, http://blog.bruggen.com?view=mosaic[Rik], http://maxdemarzi.com[Max], http://www.markhneedham.com/blog/category/databases-2/neo4j/[Mark], http://www.kennybastani.com/[Kenny], http://jexp.de/blog[Michael], http://iansrobinson.com/[Ian], http://jimwebber.org/[Jim], ...)
* http://neo4j.com/events?type=Meetup[Local Meetup Groups]
* http://watch.neo4j.org[Webinar/Talk Recordings]

=== Exemple d'application par langage, couche ou driver

Afin d'expliquer l'usage de Neo4j à travers différents langages de programmation, nous proposons une section d'introduction par
langage se trouvant dans le répertoire `language-guides/<language>/<language>.adoc`.

Pour montrer comment les différents drivers pour ce langage seraient utilisés/intégrés, nous disposons aussi d'exemples de projets/installations dans le répertoire `language-guides/<language>/<driver>` 

L'application d'exemple est une simple application mono-page basée sur le jeu de données Neo4j-Movies qui est livré avec Neo4j-Server (`:play movies` dans le Neo4j-Browser).

Vous pouvez voir un exemple http://my-neo4j-movies-app.herokuapp.com/[ici sur heroku].

La page HTML utilise des requêtes ajax jQuery afin de requêter 3 endpoints REST dans le backend pour `/search`, `/movie` et `/graph`

* `/search` liste les films trouvés par titre
* `/movie` retourne les détails d'un seul film
* `/graph` retourne le rendu du graphe comme une visualisation d3 simple

Ceci est la liste des projets actuels:

* java/jdbc
* java/server-extension
* python/py2neo (Thanks Nigel & Mark)
* python/neo4j-rest-client (Thanks Javier)
* clojure/neocons (Thanks Rohit)
* go/cq (Thanks Wes)
* perl/neo4p (Thanks Mark)
* php/neoclient (Thanks Christophe)
* php/neo4jphp (Thanks Josh)
* ruby/neo4jrb and ruby/neo4j-core (Thanks Andreas)
* donet/neo4jclient (Thanks Pierrick)

